apiVersion: v1
kind: Service
metadata:
  name: broker-service
  namespace: orderly
spec:
  type: ClusterIP
  selector:
    app: broker
  ports:
  - protocol: TCP
    name: 'rabbitmq'
    port: 5672 # Porta para conexões RabbitMQ
    targetPort: 5672
---
apiVersion: v1
kind: Service
metadata:
  name: broker-service-cp
  namespace: orderly
spec:
  type: NodePort
  selector:
    app: broker
  ports:
  - protocol: TCP
    name: 'rabbitmq-controlpanel'
    port: 15672 # Porta para o painel de controle do RabbitMQ
    targetPort: 15672
    nodePort: 30672
