apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: orderly
spec:
  type: NodePort # LoadBalancer if you running on cloud
  selector:
    app: api
  ports:
  - protocol: TCP
    port: 3000
    nodePort: 30000
