apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  namespace: orderly
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api-container
        image: dealmachine/hexagonal-architecture-api:4
        workingDir: /api
        resources:
          requests: # requisita recursos
            memory: '500Mi'
            cpu: '1'
          limits: # limita a utilização dos recursos
            memory: "500Mi"
            cpu: "1"
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: api-configmap
        startupProbe:
          httpGet:
            path: /orders
            port: 3000
          periodSeconds: 5
          failureThreshold: 30
        readinessProbe:
          httpGet:
            path: /orders
            port: 3000
          periodSeconds: 3
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /orders
            port: 3000
          periodSeconds: 10 # perido de tempo para cada requisição
          timeoutSeconds: 3 # tempo de espera por requisição
          failureThreshold: 3 # quantidade de falhas para reiniciar
