apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: orderly
spec:
  type: ClusterIP # NodePort if you running locally
  selector:
    app: api
  ports:
  - protocol: TCP
    port: 3000
